### ISSUE TITLE
Current Map Layers sources (polygons) disappears when an map style is selected 

### ISSUE THREAD

**Issue by joaoGabriel55** [el/style-switcher#19] opened 2022-04-07 12:24 UTC
Current style:

![image](https://user-images.githubusercontent.com/23138717/162197685-520e1048-1d57-441b-b495-3265d8216eac.png)

Selected style:

![image](https://user-images.githubusercontent.com/23138717/162197803-9d9bc8a4-4432-4899-8a1c-a8b92e5a1d4d.png)

**Comment by el** [comment] 2022-04-07 12:40
You need to re-add them

**Comment by joaoGabriel55** [comment] 2022-04-07 18:03
How can I do this? Cause I did this but I do not know if was the correct way. I used localstorage to save the old state, but when I tried to re-add again did not works.

**Comment by el** [comment] 2022-04-08 09:31
You can add an event handler to your maps `load` and `style.load` events 
```js
            map.on("load", () => { /* add your logic */ });
            map.on("style.load", () => { /* add your logic */ });
```

I am closing this issue since this is not a bug or a feature request.

**Closed as completed by el** 2022-04-08 09:31 UTC

**Comment by joaoGabriel55** [comment] 2022-04-08 11:13
> You can add an event handler to your maps `load` and `style.load` events
> 
> ```js
>             map.on("load", () => { /* add your logic */ });
>             map.on("style.load", () => { /* add your logic */ });
> ```
> 
> I am closing this issue since this is not a bug or a feature request.

Oh, awesome!!! thank you very much, I will try this solution. But I solved using a setTimeout that loads the layers with some little delay.

**Comment by chriszrc** [comment] 2023-01-05 21:53
I've created a fork with a new option for "preserveLayers":

https://github.com/chriszrc/style-switcher

It automatically retains all user-added layers/sources while switching between road/satellite/etc styles. I think I've covered all the edge cases, but if you try it out and find any problems let me know and then maybe I will create a pull request-
